# Automate configuration file
# https://github.com/TheLuca98/Automate

PistonBreakModule:
  # If enabled, pistons with attached end rod break blocks
  enabled: true

DispenserPlaceModule:
  # If enabled, dispensers will try to place down blocks
  enabled: true
  # Dispensers will retain vanilla behavior for all materials in this list
  ignore:
    - minecraft:tnt
    - minecraft:carved_pumpkin
    - minecraft:creeper_head
    - minecraft:dragon_head
    - minecraft:piston_head
    - minecraft:player_head
    - minecraft:zombie_head
    - minecraft:black_shulker_box
    - minecraft:blue_shulker_box
    - minecraft:brown_shulker_box
    - minecraft:cyan_shulker_box
    - minecraft:gray_shulker_box
    - minecraft:green_shulker_box
    - minecraft:light_blue_shulker_box
    - minecraft:light_gray_shulker_box
    - minecraft:lime_shulker_box
    - minecraft:magenta_shulker_box
    - minecraft:orange_shulker_box
    - minecraft:pink_shulker_box
    - minecraft:purple_shulker_box
    - minecraft:red_shulker_box
    - minecraft:shulker_box
    - minecraft:white_shulker_box
    - minecraft:yellow_shulker_box
  # Mappings can turn items into corresponding blocks (e.g. crops)
  mappings:
    - from: minecraft:wheat_seeds
      to: minecraft:wheat
    - from: minecraft:carrot
      to: minecraft:carrots
    - from: minecraft:potato
      to: minecraft:potatoes
    - from: minecraft:beetroot_seeds
      to: minecraft:beetroots
    - from: minecraft:melon_seeds
      to: minecraft:melon_stem
    - from: minecraft:pumpkin_seeds
      to: minecraft:pumpkin_stem